/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* creation time: Wed Jan 14 13:34:07 2015 */
/* tdr version: 2.7.4, build at 20150114 */


using System;
using System.Diagnostics;

namespace GCloudTdr
{



public class TdrDebug
{
    public static void tdrTrace()
    {
        StackTrace st = new StackTrace(true);
        for (int i = 1; i < st.FrameCount; i++)
        {
            if (null != st.GetFrame(i).GetFileName())
            {
                Console.WriteLine("TSF4G_TRACE:  " + st.GetFrame(i).ToString());
            }
        }
    }
}

}
