/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* creation time: Wed Jan 14 13:34:07 2015 */
/* tdr version: 2.7.4, build at 20150114 */

using System;

namespace GCloudTdr
{


public interface IPackable
{
    /* useVarInt: variable-length integer encode or not */
    TdrError.ErrorType packTLV(ref Byte[] buffer, Int32 size, ref Int32 used, Boolean useVarInt);
}

public interface IUnpackable
{
    TdrError.ErrorType unpackTLV(ref Byte[] buffer, Int32 size, ref Int32 used);
}


}
