// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using UnityEngine;

namespace GCloud
{
    public delegate void LogHandler(LogPriority pri, string msg);

    public abstract class IGCloud
    {
		protected IGCloud()
        {
        }
        
		static private IGCloud instance = null;
		static public IGCloud Instance
        {
            get
            {
                if(instance == null)
                {
                    instance = new GCloud();
                }

                return instance;
            }
        }
        
		public abstract void SetLogger(LogPriority pri, LogHandler callback);
        
		public abstract Result Initialize(InitializeInfo initInfo);

		public abstract bool SwitchPlugin(string pluginName);

		public abstract IConnector CreateConnector(ConnectorType type, bool manualUpdate, bool autoReconnect, bool autoLogin);

		public abstract void DestroyConnector(IConnector Connector);

		public abstract void SetUserInfo (UserInfo userInfo);
    }
	
	public class InitializeInfo : ApolloBufferBase
	{
		public string PluginName; // Obsolete
        public Int64 GameId;
		public string GameKey;
		
		public InitializeInfo(Int64 gameId, string gameKey)
		{
			GameId = gameId;
			GameKey = gameKey;
		}
		
		public override void WriteTo(ApolloBufferWriter writer)
		{
			writer.Write(PluginName);
			writer.Write(GameId);
			writer.Write(GameKey);
		}
		
		public override void ReadFrom(ApolloBufferReader reader)
		{
			reader.Read(ref PluginName);
			reader.Read(ref GameId);
			reader.Read(ref GameKey);
		}
	}

}

